### ISSUE TITLE
PersistedOffsetAkka mechanism inefficient 

### ISSUE THREAD

**Issue by jasongoodwin** [fun-cqrs/fun-cqrs#85]
The PersistedOffserAkka mechanism calls `deleteMessages(seqNrToDelete)` which looks like this in Akka Persistence:

``` 
 def deleteMessages(toSequenceNr: Long): Unit =
    journal ! DeleteMessagesTo(persistenceId, toSequenceNr, self)
```

Which will check all of the records to see if any need to be updated.
This is executed on every offset update.

**Comment by jasongoodwin** [comment]
I guess this is only relevant for M1 - looks like it's deprecated in M2

**Comment by rcavalcanti** [comment]
Yes, the `PersistedOffsetAkka` was a terrible idea. Initially offset were not deleted, but I got some systems where this was producing too much garbage. If you have 500000 events and 5 projections you get 2.5 millions events that had no business value. Hence the idea to delete it. 

I would rather remove it and have extensions points providing `OffsetPersistenceStrategies` for different DBs. 

DB specific strategies could also provide exactly-once semantics. For instance, a Slick one would look like:

```
class SlickOffsetPersistenceStrategy(db: Database) extends CustomOffsetPersistenceStrategy[O] {

   /** Saves nothing and let Projection save the offset in same tx as read-model */
  def saveCurrentOffset(offset: O): Future[Unit] = Future.successful(())

  def readOffset: Future[Option[O]] = ??? // implement the query to fetch the latest offset
}
```

Since 1.0.0-M2, it's possible to receive the Offset in the Projection. A Slick based Projection can then save the offset together with the model and achieve exactly-once semantics.

The same could be done for a Cassandra projection.

**Comment by jasongoodwin** [comment]
Hmm okay - this is helpful info for understanding what's happening behind
the abstractions - The delete only marks it deleted in the db with the pg
backend we use (maybe not true with every journal plugin) so it has to go
through each event and check if it's already deleted the events (eg delete
is 'soft' ). Im realizing that the combination of the deletes with the
specific backend might be strictly worse for us so we could also consider
forking funcqrs and not deleting it with the cost being that the recovery
is slow (instead of each event on the aggregate being slow as it's trying
to delete 100ks of records).

At least until we can get to m2.

**Comment by rcavalcanti** [comment]
@jasongoodwin I'll be glad to see you forking and contributing. But this is not something to solve with a fork. You can use your own `OffsetPersistenceStrategy`.

You can make one based on akka-persistence that never deletes. Or one that save the offset as a snapshot. But the best one is to use postgres and ave the offset in table. 

As I said, `PersistedOffsetAkka` is a bad idea and I hope to delete it in the future.

**Comment by rcavalcanti** [comment]
Ok, I got your point. You are on M1. 

You can still use your own strategy. Akka or Postgres based. What you won't get in M1 is the possibility to have something with `exactly-once` semantics

**Comment by jasongoodwin** [comment]
yeah just for anyone who stumbles on this thread in the future, I just log the offset elsewhere with a custom strategy.
