### ISSUE TITLE
Future of fun-cqrs

### ISSUE THREAD

**Issue by firehooper** [fun-cqrs/fun-cqrs#93]
Hello @cvanfleteren .  We are trying to decide whether to switch our application (not yet in production) from fun-cqrs to lagom.  Is https://github.com/WegenenVerkeer/fun-cqrs the new source of truth for this project?  What are your long term plans for maintaining this project and do you have applications in production using it?

**Comment by renatocaval** [comment]
I'm won't be supporting Fun.CQRS myself anymore as I have joined Lightbend and I'm now working on the Lagom team. I do accept PRs and make releases for this project whenever asked. 

I'm surprised that my ex-colleagues at AWV have forked it and are not contributing back. @cvanfleteren  / @rigolepe, really? Why?  You both are maintainers of this repo. You can add features, fix bugs, review and merge the PRs. Why a fork that is not being merged back?
The only thing that could be annoying is depending on me for the releases, but that we can solve as well. 

Now, @firehooper, if you ask me which one to choose, I will say Lagom. Not because I have any contractual obligations to say so, but because Lagom is being backed by Lightbend and we have a dedicated team working on it. 

It's sad for me to say that. Fun.CQRS is my baby and it has an elegant architecture based on higher-kinds and interpreters. And I had a great time in building it. But as of today, I can't promise you any other future for it than what I mentioned above, ie: accepting PRs and making releases. 

I'll be glad to hand it over.

**Comment by rigolepe** [comment]
Hello Renato and @firehooper ,

The AWV fork is not supposed to be the official repo, it's where we commit our changes that we want to test & deploy quickly. It allows us to cycle fast so that we don't have to wait for official releases to fix things and do new stuff. We have many production systems on fun.cqrs, and we just have to be able to move quickly when we have to. 

Bugfixes have been merged back into the strongtyped repo in the past and we should continue to do just that. Sometimes it is better to wait till changes have been tested thoroughly, so in certain cases I expect we may want to wait a bit before merging changes back to the strongtyped repo. But, you're right that our recent changes haven't been contributed yet, and I'll see to it that we do this soon and keep on doing it in the future! 

If you prefer us working directly on the official repo, that's fine too... as long as we can agree to a workflow that doesn't hinder us in any way (even when we just want to experiment). 

cheers,
   Peter

**Comment by renatocaval** [comment]
@rigolepe, I have no problem if you use the official repo for this. It could be better to push your experimentations to a branch here and keep the `develop` branch clean. 

Maybe we should move out fun.cqrs from the `io.strongtyped` domain / package and you guys take it over and even do the release management. That's all fine by me.

**Comment by rigolepe** [comment]
Hi @renatocaval, 

I see no problem for us taking over the release management. Then we can drop our internal builds and release directly in the public domain. This way, it could be easier to keep the project alive as well. I'll discuss it in the team asap. 

Could you briefly document the current release process? Then we can see how we can integrate it best in our workflow... Maybe we can take this offline until we worked out a solution before announcing anything on github.

**Comment by renatocaval** [comment]
@firehooper FYI, I moved  fun-cqrs from `strongtyped` organisation to `fun-cqrs` organisation and @rigolepe is now member of `fun-cqrs` org as well. 

Next step is to rename the package name and maven group id to detach it from Strong[Typed]. The release cycle will be managed by my old colleagues at AWV where @rigolepe is the team leader.

I'm closing this issue...
